Repository AY2021S1-CS2103T-T10-1/tp, pull requests merged in 2020-11, with the labels that each got.

#200 Change the function of c/ in sort command
  src/main/java/seedu/momentum/logic/commands/SortCommand.java
  src/main/java/seedu/momentum/logic/parser/SortCommandParser.java
  src/main/java/seedu/momentum/model/Model.java
  src/main/java/seedu/momentum/model/ModelManager.java
  src/main/java/seedu/momentum/model/VersionedProjectBook.java
  src/main/java/seedu/momentum/model/project/Project.java
  src/test/java/seedu/momentum/logic/commands/CommandTestUtil.java
  src/test/java/seedu/momentum/logic/commands/SortCommandTest.java
  src/test/java/seedu/momentum/logic/parser/ProjectBookParserTest.java
  src/test/java/seedu/momentum/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/momentum/model/project/UniqueTrackedItemListTest.java
  src/test/java/seedu/momentum/testutil/SortCommandUtil.java
Labels: priority.Medium, type.Enhancement

#205 Add tests
  src/main/java/seedu/momentum/AppParameters.java
  src/main/java/seedu/momentum/MainApp.java
  src/main/java/seedu/momentum/commons/core/DateTimeWrapper.java
  src/main/java/seedu/momentum/commons/core/LogsCenter.java
  src/main/java/seedu/momentum/commons/util/JsonUtil.java
  src/main/java/seedu/momentum/logic/parser/AddCommandParser.java
  src/main/java/seedu/momentum/model/ModelManager.java
  src/main/java/seedu/momentum/model/ProjectBook.java
  src/main/java/seedu/momentum/model/project/Deadline.java
  src/main/java/seedu/momentum/model/project/Description.java
  src/main/java/seedu/momentum/model/reminder/ReminderManager.java
  src/main/java/seedu/momentum/storage/JsonProjectBookStorage.java
  src/main/java/seedu/momentum/storage/StorageManager.java
  src/main/java/seedu/momentum/ui/DurationListPanel.java
  src/main/java/seedu/momentum/ui/HelpWindow.java
  src/main/java/seedu/momentum/ui/TrackedItemListPanel.java
  src/main/java/seedu/momentum/ui/UiManager.java
  src/test/java/seedu/momentum/AppParametersTest.java
  src/test/java/seedu/momentum/commons/core/DateTimeWrapperTest.java
  src/test/java/seedu/momentum/commons/core/DateWrapperTest.java
  src/test/java/seedu/momentum/commons/core/TimeWrapperTest.java
  src/test/java/seedu/momentum/logic/commands/CommandTestUtil.java
  src/test/java/seedu/momentum/logic/commands/SortCommandTest.java
  src/test/java/seedu/momentum/model/ProjectBookTest.java
  src/test/java/seedu/momentum/model/project/CompletionStatusTest.java
  src/test/java/seedu/momentum/model/project/DeadlineTest.java
  src/test/java/seedu/momentum/model/project/DescriptionTest.java
  src/test/java/seedu/momentum/model/project/predicates/CompletionStatusPredicateTest.java
  src/test/java/seedu/momentum/model/reminder/ReminderTest.java
  src/test/java/seedu/momentum/model/util/SampleDataUtilTest.java
  src/test/java/seedu/momentum/testutil/ProjectBuilder.java
Labels: priority.Medium

#208 Add additional tests
  src/main/java/seedu/momentum/model/reminder/Reminder.java
  src/main/java/seedu/momentum/model/reminder/ReminderManager.java
  src/test/java/seedu/momentum/commons/core/DateTimeWrapperTest.java
  src/test/java/seedu/momentum/commons/core/DateWrapperTest.java
  src/test/java/seedu/momentum/commons/core/TimeWrapperTest.java
  src/test/java/seedu/momentum/model/ProjectBookTest.java
  src/test/java/seedu/momentum/model/project/CompletionStatusTest.java
  src/test/java/seedu/momentum/model/project/DeadlineTest.java
  src/test/java/seedu/momentum/model/project/DescriptionTest.java
  src/test/java/seedu/momentum/model/project/NameTest.java
  src/test/java/seedu/momentum/model/project/predicates/CompletionStatusPredicateTest.java
  src/test/java/seedu/momentum/model/project/predicates/DescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/momentum/model/project/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/momentum/model/project/predicates/TagListContainsKeywordsPredicateTest.java
  src/test/java/seedu/momentum/model/reminder/ReminderManagerTest.java
  src/test/java/seedu/momentum/model/reminder/ReminderTest.java
  src/test/java/seedu/momentum/model/tag/TagTest.java
Labels: priority.Medium, severity.Medium

#209 Fix stats calculation
  src/main/java/seedu/momentum/commons/core/DateTimeWrapper.java
  src/main/java/seedu/momentum/logic/statistic/PeriodicTotalTimeStatistic.java
Labels: type.Task

#212 Add show command support for tags
  src/main/java/seedu/momentum/logic/Logic.java
  src/main/java/seedu/momentum/logic/LogicManager.java
  src/main/java/seedu/momentum/logic/commands/ShowComponentCommand.java
  src/main/java/seedu/momentum/logic/parser/ShowComponentCommandParser.java
  src/main/java/seedu/momentum/model/Model.java
  src/main/java/seedu/momentum/model/ModelManager.java
  src/main/java/seedu/momentum/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/momentum/logic/commands/AddCommandTest.java
  src/test/java/seedu/momentum/logic/commands/ShowComponentCommandTest.java
  src/test/java/seedu/momentum/logic/parser/ProjectBookParserTest.java
  src/test/java/seedu/momentum/logic/parser/ShowComponentCommandParserTest.java
Labels: priority.Medium

#213 Add bottom bar
  docs/images/Ui.png
  src/main/java/seedu/momentum/logic/Logic.java
  src/main/java/seedu/momentum/logic/LogicManager.java
  src/main/java/seedu/momentum/model/Model.java
  src/main/java/seedu/momentum/model/ModelManager.java
  src/main/java/seedu/momentum/ui/BottomBar.java
  src/main/java/seedu/momentum/ui/MainWindow.java
  src/main/resources/view/BottomBar.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MomentumDark.css
  src/test/java/seedu/momentum/logic/commands/AddCommandTest.java
Labels: priority.Medium

#229 Feature issue 227
  src/main/java/seedu/momentum/model/Model.java
  src/main/java/seedu/momentum/model/ModelManager.java
  src/test/java/seedu/momentum/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/momentum/logic/commands/AddProjectCommandTest.java
Labels: priority.High, severity.High, type.Bug

#231 Make reminder expire if not scheduled
  src/main/java/seedu/momentum/commons/core/DateTimeWrapper.java
  src/main/java/seedu/momentum/commons/core/ThreadWrapper.java
  src/main/java/seedu/momentum/logic/commands/AddTaskCommand.java
  src/main/java/seedu/momentum/logic/commands/DismissCommand.java
  src/main/java/seedu/momentum/logic/commands/EditCommand.java
  src/main/java/seedu/momentum/logic/commands/ShowComponentCommand.java
  src/main/java/seedu/momentum/logic/parser/ShowComponentCommandParser.java
  src/main/java/seedu/momentum/model/Model.java
  src/main/java/seedu/momentum/model/ModelManager.java
  src/main/java/seedu/momentum/model/ProjectBook.java
  src/main/java/seedu/momentum/model/project/Project.java
  src/main/java/seedu/momentum/model/project/Task.java
  src/main/java/seedu/momentum/model/project/TrackedItem.java
  src/main/java/seedu/momentum/model/project/predicates/CompletionStatusPredicate.java
  src/main/java/seedu/momentum/model/reminder/Reminder.java
  src/main/java/seedu/momentum/model/reminder/ReminderManager.java
  src/main/java/seedu/momentum/storage/JsonAdaptedProject.java
  src/main/java/seedu/momentum/storage/JsonAdaptedTask.java
  src/main/java/seedu/momentum/storage/JsonToModel.java
  src/main/java/seedu/momentum/ui/TrackedItemCard.java
  src/test/java/seedu/momentum/logic/LogicManagerTest.java
  src/test/java/seedu/momentum/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/momentum/logic/commands/AddProjectCommandTest.java
  src/test/java/seedu/momentum/logic/commands/DismissCommandTest.java
  src/test/java/seedu/momentum/logic/commands/EditProjectCommandTest.java
  src/test/java/seedu/momentum/logic/commands/ListCommandTest.java
  src/test/java/seedu/momentum/logic/commands/ShowComponentCommandTest.java
  src/test/java/seedu/momentum/logic/parser/ParserUtilTest.java
  src/test/java/seedu/momentum/logic/parser/ProjectBookParserTest.java
  src/test/java/seedu/momentum/logic/parser/ShowComponentCommandParserTest.java
  src/test/java/seedu/momentum/model/project/predicates/CompletionStatusPredicateTest.java
  src/test/java/seedu/momentum/model/reminder/ReminderManagerTest.java
  src/test/java/seedu/momentum/model/reminder/ReminderTest.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#242 Add undo, redo, sort tests
  docs/team/kkangs0226.md
  src/main/java/seedu/momentum/model/Model.java
  src/main/java/seedu/momentum/model/ModelManager.java
  src/main/java/seedu/momentum/model/ProjectBookWithUi.java
  src/main/java/seedu/momentum/model/VersionedProjectBook.java
  src/main/java/seedu/momentum/model/project/comparators/NameCompare.java
  src/main/resources/view/TimerCard.fxml
  src/main/resources/view/TimerListPanel.fxml
  src/test/java/seedu/momentum/logic/commands/AddProjectCommandTest.java
  src/test/java/seedu/momentum/logic/commands/CommandTestUtil.java
  src/test/java/seedu/momentum/logic/commands/HomeCommandTest.java
  src/test/java/seedu/momentum/logic/commands/UndoCommandTest.java
  src/test/java/seedu/momentum/model/ModelManagerTest.java
  src/test/java/seedu/momentum/model/ProjectBookWithUiTest.java
  src/test/java/seedu/momentum/model/VersionedProjectBookTest.java
  src/test/java/seedu/momentum/model/project/comparators/CompletionStatusCompareTest.java
  src/test/java/seedu/momentum/model/project/comparators/NameCompareTest.java
  src/test/java/seedu/momentum/testutil/TypicalProjects.java
  src/test/java/seedu/momentum/testutil/TypicalProjectsOrders.java
Labels: priority.Medium

#243 Add tests and make CompletionsStatusPredicate inherit from ContainsKeywordPredicate
  src/main/java/seedu/momentum/model/project/Deadline.java
  src/main/java/seedu/momentum/model/project/predicates/CompletionStatusPredicate.java
  src/main/java/seedu/momentum/model/project/predicates/ContainsKeywordPredicate.java
Labels: priority.Medium, severity.Medium

#230 Settings undo redo
  src/main/java/seedu/momentum/logic/SettingsUpdateManager.java
  src/main/java/seedu/momentum/logic/commands/SetCommand.java
  src/main/java/seedu/momentum/model/ModelManager.java
  src/main/java/seedu/momentum/model/ProjectBookWithUi.java
  src/main/java/seedu/momentum/model/UserPrefs.java
  src/main/java/seedu/momentum/model/VersionedProjectBook.java
  src/main/java/seedu/momentum/ui/MainWindow.java
  src/test/java/seedu/momentum/logic/commands/AddProjectCommandTest.java
  src/test/java/seedu/momentum/model/ProjectBookWithUiTest.java
  src/test/java/seedu/momentum/model/VersionedProjectBookTest.java
Labels: severity.High, type.Bug

#244 Fix Time Formating Bug
  src/main/java/seedu/momentum/commons/util/StringUtil.java
  src/main/java/seedu/momentum/logic/commands/StopProjectCommand.java
  src/main/java/seedu/momentum/logic/commands/StopTaskCommand.java
  src/main/java/seedu/momentum/ui/StatCard.java
  src/test/java/seedu/momentum/logic/commands/StopCommandTest.java
  src/test/java/seedu/momentum/logic/commands/StopTaskCommandTest.java
Labels: priority.Medium, severity.Medium, type.Bug

#249 Fix reminder related bugs
  src/main/java/seedu/momentum/model/ModelManager.java
  src/main/java/seedu/momentum/model/reminder/ReminderManager.java
  src/main/java/seedu/momentum/ui/MainWindow.java
  src/main/java/seedu/momentum/ui/ReminderDisplay.java
  src/main/java/seedu/momentum/ui/TrackedItemCard.java
  src/main/resources/view/ReminderDisplay.fxml
Labels: priority.High, severity.High, type.Bug

#263 Add diagrams and update Developer's Guide.
  docs/DeveloperGuide.md
  docs/diagrams/EditDeadlineSequenceDiagram.puml
  docs/diagrams/ReminderClassDiagram.puml
  docs/diagrams/RunTaskReminderSequenceDiagram.puml
  docs/diagrams/ScheduleReminderSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/EditDeadlineSequenceDiagram.png
  docs/images/ReminderClassDiagram.png
  docs/images/RunTaskReminderSequenceDiagram.png
  docs/images/ScheduleReminderSequenceDiagram.png
  docs/images/StorageClassDiagram.png
Labels: doc.DevGuide, priority.Medium

#265 Update User Guide
  docs/UserGuide.md
Labels: doc.UserGuide

#269 Add step by step descriptions for user guide and update command summary
  docs/UserGuide.md
  docs/images/AddProjectDiagram1.png
  docs/images/AddProjectDiagram2.png
  docs/images/AddProjectDiagram3.png
  docs/images/AddProjectDiagram4.png
  docs/images/DismissDiagram1.png
  docs/images/DismissDiagram2.png
  docs/images/DismissDiagram3.png
  docs/images/EditTaskDiagram1.png
  docs/images/EditTaskDiagram2.png
  docs/images/EditTaskDiagram3.png
  docs/images/ShowDiagram1.png
  docs/images/ShowDiagram2.png
  docs/images/ShowDiagram3.png
  src/main/java/seedu/momentum/commons/util/StringUtil.java
  src/main/resources/data/defaultData.json
Labels: doc.UserGuide, priority.Medium

#274 Update todos for developer guide
  docs/DeveloperGuide.md
  docs/diagrams/EditDeadlineSequenceDiagram.puml
  docs/diagrams/ReminderClassDiagram.puml
  docs/diagrams/RunTaskReminderSequenceDiagram.puml
  docs/diagrams/ScheduleReminderSequenceDiagram.puml
  docs/diagrams/ScheduleReminderSequenceDiagramRescheduleReminderProject.puml
  docs/diagrams/ScheduleReminderSequenceDiagramUpdateExpiredReminders.puml
  docs/images/EditDeadlineSequenceDiagram.png
  docs/images/ReminderClassDiagram.png
  docs/images/RunTaskReminderSequenceDiagram.png
  docs/images/ScheduleReminderSequenceDiagram.png
  docs/images/ScheduleReminderSequenceDiagramRescheduleReminderProject.png
  docs/images/ScheduleReminderSequenceDiagramUpdateExpiredReminders.png
Labels: doc.DevGuide, priority.Medium

#280 Update user guide
  docs/UserGuide.md
Labels: doc.DevGuide, priority.Medium

#286 Developer guide
  docs/diagrams/ReminderClassDiagram.puml
  docs/diagrams/ScheduleReminderSequenceDiagram.puml
  docs/diagrams/ScheduleReminderSequenceDiagramRescheduleReminderProject.puml
  docs/diagrams/ScheduleReminderSequenceDiagramUpdateExpiredReminders.puml
  docs/images/ReminderClassDiagram.png
  src/main/java/seedu/momentum/logic/commands/Command.java
  src/test/java/seedu/momentum/logic/commands/CommandTestUtil.java
Labels: doc.DevGuide, priority.Medium
