Repository AY2021S1-CS2103T-T10-1/tp, pull requests merged in 2020-10, with the labels that each got.

#38 Add creation date and deadline
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/momentum/commons/core/Clock.java
  src/main/java/seedu/momentum/commons/core/Date.java
  src/main/java/seedu/momentum/commons/core/DateTime.java
  src/main/java/seedu/momentum/commons/core/Instance.java
  src/main/java/seedu/momentum/commons/core/Time.java
  src/main/java/seedu/momentum/commons/util/DateTimeUtil.java
  src/main/java/seedu/momentum/commons/util/DateUtil.java
  src/main/java/seedu/momentum/commons/util/TimeUtil.java
  src/main/java/seedu/momentum/logic/commands/AddCommand.java
  src/main/java/seedu/momentum/logic/commands/EditCommand.java
  src/main/java/seedu/momentum/logic/parser/AddCommandParser.java
  src/main/java/seedu/momentum/logic/parser/CliSyntax.java
  src/main/java/seedu/momentum/logic/parser/EditCommandParser.java
  src/main/java/seedu/momentum/logic/parser/ParserUtil.java
  src/main/java/seedu/momentum/model/project/Deadline.java
  src/main/java/seedu/momentum/model/project/Project.java
  src/main/java/seedu/momentum/model/timer/DurationUtil.java
  src/main/java/seedu/momentum/model/timer/Time.java
  src/main/java/seedu/momentum/model/timer/Timer.java
  src/main/java/seedu/momentum/model/timer/WorkDuration.java
  src/main/java/seedu/momentum/model/util/SampleDataUtil.java
  src/main/java/seedu/momentum/storage/JsonAdaptedDeadline.java
  src/main/java/seedu/momentum/storage/JsonAdaptedProject.java
  src/main/java/seedu/momentum/storage/JsonAdaptedTimer.java
  src/main/java/seedu/momentum/storage/JsonAdaptedWorkDuration.java
  src/main/java/seedu/momentum/ui/DurationCard.java
  src/main/java/seedu/momentum/ui/ProjectCard.java
  src/main/resources/view/ProjectListCard.fxml
  src/test/data/JsonSerializableProjectBookTest/duplicateProjectProjectBook.json
  src/test/data/JsonSerializableProjectBookTest/typicalProjectsProjectBook.json
  src/test/java/seedu/momentum/commons/core/DateTest.java
  src/test/java/seedu/momentum/commons/core/DateTimeTest.java
  src/test/java/seedu/momentum/commons/core/TimeTest.java
  src/test/java/seedu/momentum/logic/LogicManagerTest.java
  src/test/java/seedu/momentum/logic/commands/CommandTestUtil.java
  src/test/java/seedu/momentum/logic/commands/EditCommandTest.java
  src/test/java/seedu/momentum/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/momentum/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/momentum/logic/parser/ParserUtilTest.java
  src/test/java/seedu/momentum/logic/parser/ProjectBookParserTest.java
  src/test/java/seedu/momentum/model/project/DeadlineTest.java
  src/test/java/seedu/momentum/model/project/ProjectTest.java
  src/test/java/seedu/momentum/model/timer/TimeTest.java
  src/test/java/seedu/momentum/model/timer/WorkDurationTest.java
  src/test/java/seedu/momentum/storage/JsonAdaptedDeadlineTest.java
  src/test/java/seedu/momentum/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/momentum/storage/JsonAdaptedTimerTest.java
  src/test/java/seedu/momentum/storage/JsonAdaptedWorkDurationTest.java
  src/test/java/seedu/momentum/storage/JsonSerializableProjectBookTest.java
  src/test/java/seedu/momentum/testutil/EditProjectDescriptorBuilder.java
  src/test/java/seedu/momentum/testutil/ProjectBuilder.java
  src/test/java/seedu/momentum/testutil/ProjectUtil.java
  src/test/java/seedu/momentum/testutil/TypicalProjects.java
  src/test/java/seedu/momentum/testutil/TypicalTimes.java
Labels: doc.DevGuide, doc.UserGuide, priority.Medium, type.Epic

#40 Implement Statistics Logic
  src/main/java/seedu/momentum/commons/core/DateTime.java
  src/main/java/seedu/momentum/logic/Logic.java
  src/main/java/seedu/momentum/logic/LogicManager.java
  src/main/java/seedu/momentum/logic/commands/StartCommand.java
  src/main/java/seedu/momentum/logic/commands/StopCommand.java
  src/main/java/seedu/momentum/logic/statistic/PeriodicTotalTimePerProjectStatistic.java
  src/main/java/seedu/momentum/logic/statistic/Statistic.java
  src/main/java/seedu/momentum/logic/statistic/StatisticEntry.java
  src/main/java/seedu/momentum/logic/statistic/StatisticGenerator.java
  src/main/java/seedu/momentum/logic/statistic/StatisticManager.java
  src/main/java/seedu/momentum/ui/MainWindow.java
  src/main/java/seedu/momentum/ui/TestStatWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TestStatWindow.fxml
  src/test/java/seedu/momentum/logic/commands/CommandTestUtil.java
  src/test/java/seedu/momentum/logic/commands/StartCommandTest.java
  src/test/java/seedu/momentum/logic/commands/StopCommandTest.java
  src/test/java/seedu/momentum/logic/parser/StartCommandParserTest.java
  src/test/java/seedu/momentum/logic/parser/StopCommandParserTest.java
  src/test/java/seedu/momentum/logic/statistic/PeriodicTotalTimePerProjectStatisticTest.java
  src/test/java/seedu/momentum/logic/statistic/StatisticEntryTest.java
  src/test/java/seedu/momentum/logic/statistic/StatisticManagerTest.java
  src/test/java/seedu/momentum/logic/statistic/StatisticTestUtil.java
Labels: priority.Medium

#44 Improve find command
  docs/UserGuide.md
  src/main/java/seedu/momentum/commons/util/StringUtil.java
  src/main/java/seedu/momentum/logic/commands/FindCommand.java
  src/main/java/seedu/momentum/logic/parser/CliSyntax.java
  src/main/java/seedu/momentum/logic/parser/FindCommandParser.java
  src/main/java/seedu/momentum/model/project/NameContainsKeywordsPredicate.java
  src/main/java/seedu/momentum/model/project/predicates/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/momentum/model/project/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/momentum/model/project/predicates/TagListContainsKeywordsPredicate.java
  src/test/java/seedu/momentum/commons/util/StringUtilTest.java
  src/test/java/seedu/momentum/logic/commands/CommandTestUtil.java
  src/test/java/seedu/momentum/logic/commands/FindCommandTest.java
  src/test/java/seedu/momentum/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/momentum/logic/parser/ProjectBookParserTest.java
  src/test/java/seedu/momentum/model/ModelManagerTest.java
  src/test/java/seedu/momentum/model/project/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/momentum/model/project/predicates/DescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/momentum/model/project/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/momentum/model/project/predicates/TagListContainsKeywordsPredicateTest.java
Labels: doc.UserGuide, priority.Medium, type.Epic, type.Story

#45 Improve GUI
  src/main/java/seedu/momentum/model/ProjectBook.java
  src/main/java/seedu/momentum/model/ReadOnlyProjectBook.java
  src/main/java/seedu/momentum/model/project/Deadline.java
  src/main/java/seedu/momentum/model/project/Description.java
  src/main/java/seedu/momentum/ui/HelpWindow.java
  src/main/java/seedu/momentum/ui/InfoDisplay.java
  src/main/java/seedu/momentum/ui/MainWindow.java
  src/main/java/seedu/momentum/ui/ProjectCard.java
  src/main/java/seedu/momentum/ui/StatCard.java
  src/main/java/seedu/momentum/ui/StatListPanel.java
  src/main/java/seedu/momentum/ui/StatusBarFooter.java
  src/main/java/seedu/momentum/ui/TagsDisplay.java
  src/main/resources/view/InfoDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProjectListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatCard.fxml
  src/main/resources/view/StatListPanel.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/TagsDisplay.fxml
  src/test/java/seedu/momentum/model/ProjectBookTest.java
  src/test/java/seedu/momentum/model/project/DeadlineTest.java
Labels: priority.Medium, type.Task

#49 Integrate Stats Logic with UI
  src/main/java/seedu/momentum/logic/statistic/PeriodicTotalTimeStatistic.java
  src/main/java/seedu/momentum/logic/statistic/StatisticManager.java
  src/main/java/seedu/momentum/ui/MainWindow.java
  src/main/java/seedu/momentum/ui/StatCard.java
  src/main/java/seedu/momentum/ui/StatListPanel.java
  src/main/java/seedu/momentum/ui/TestStatWindow.java
  src/test/java/seedu/momentum/logic/statistic/PeriodicTotalTimeStatisticTest.java
  src/test/java/seedu/momentum/logic/statistic/StatisticTestUtil.java
Labels: priority.Medium, type.Task

#58 Style GUI
  src/main/java/seedu/momentum/commons/core/Date.java
  src/main/java/seedu/momentum/model/project/Deadline.java
  src/main/java/seedu/momentum/ui/InfoDisplay.java
  src/main/java/seedu/momentum/ui/ProjectCard.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/InfoDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/Momentum.css
  src/main/resources/view/ProjectListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatListPanel.fxml
  src/main/resources/view/TagsDisplay.fxml
Labels: priority.Medium, type.Task

#55 Modify find command implementation
  docs/UserGuide.md
  src/main/java/seedu/momentum/logic/commands/FindCommand.java
  src/main/java/seedu/momentum/logic/parser/FindCommandParser.java
  src/main/java/seedu/momentum/model/project/predicates/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/momentum/model/project/predicates/FindType.java
  src/main/java/seedu/momentum/model/project/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/momentum/model/project/predicates/TagListContainsKeywordsPredicate.java
  src/test/java/seedu/momentum/logic/commands/CommandTestUtil.java
  src/test/java/seedu/momentum/logic/commands/FindCommandTest.java
  src/test/java/seedu/momentum/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/momentum/logic/parser/ProjectBookParserTest.java
  src/test/java/seedu/momentum/model/ModelManagerTest.java
  src/test/java/seedu/momentum/model/project/predicates/DescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/momentum/model/project/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/momentum/model/project/predicates/TagListContainsKeywordsPredicateTest.java
Labels: priority.Medium

#57 Include code coverage in README.md
  README.md
Labels: severity.VeryLow

#60 Fix Stats Data Persistence Bug
  src/main/java/seedu/momentum/logic/commands/EditCommand.java
Labels: priority.Medium, severity.Medium, type.Bug

#53 Add Sort feature
  docs/UserGuide.md
  src/main/java/seedu/momentum/commons/core/Date.java
  src/main/java/seedu/momentum/commons/core/DateTime.java
  src/main/java/seedu/momentum/commons/core/Time.java
  src/main/java/seedu/momentum/logic/commands/SortCommand.java
  src/main/java/seedu/momentum/logic/parser/CliSyntax.java
  src/main/java/seedu/momentum/logic/parser/ProjectBookParser.java
  src/main/java/seedu/momentum/logic/parser/SortCommandParser.java
  src/main/java/seedu/momentum/model/Model.java
  src/main/java/seedu/momentum/model/ModelManager.java
  src/main/java/seedu/momentum/model/ProjectBook.java
  src/main/java/seedu/momentum/model/project/Deadline.java
  src/main/java/seedu/momentum/model/project/Name.java
  src/main/java/seedu/momentum/model/project/Project.java
  src/main/java/seedu/momentum/model/project/SortType.java
  src/main/java/seedu/momentum/model/project/UniqueProjectList.java
  src/main/java/seedu/momentum/model/project/comparators/CreatedDateCompare.java
  src/main/java/seedu/momentum/model/project/comparators/DeadlineCompare.java
  src/main/java/seedu/momentum/model/project/comparators/NameCompare.java
  src/test/java/seedu/momentum/commons/core/DateTest.java
  src/test/java/seedu/momentum/commons/core/DateTimeTest.java
  src/test/java/seedu/momentum/commons/core/TimeTest.java
  src/test/java/seedu/momentum/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/momentum/logic/commands/AddCommandTest.java
  src/test/java/seedu/momentum/logic/commands/CommandTestUtil.java
  src/test/java/seedu/momentum/logic/commands/SortCommandTest.java
  src/test/java/seedu/momentum/logic/parser/ProjectBookParserTest.java
  src/test/java/seedu/momentum/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/momentum/model/ProjectBookTest.java
  src/test/java/seedu/momentum/model/project/DeadlineTest.java
  src/test/java/seedu/momentum/model/project/NameTest.java
  src/test/java/seedu/momentum/model/project/UniqueProjectListTest.java
  src/test/java/seedu/momentum/model/project/comparators/CreatedDateCompareTest.java
  src/test/java/seedu/momentum/model/project/comparators/DeadlineCompareTest.java
  src/test/java/seedu/momentum/model/project/comparators/NameCompareTest.java
  src/test/java/seedu/momentum/testutil/SortCommandUtil.java
  src/test/java/seedu/momentum/testutil/TypicalProjectsOrders.java
Labels: priority.Medium

#62 Update SortCommandParser
  docs/UserGuide.md
  src/main/java/seedu/momentum/logic/parser/SortCommandParser.java
  src/test/java/seedu/momentum/logic/parser/ProjectBookParserTest.java
  src/test/java/seedu/momentum/logic/parser/SortCommandParserTest.java
Labels: priority.Medium

#76 Add Active Timer Display
  src/main/java/seedu/momentum/logic/Logic.java
  src/main/java/seedu/momentum/logic/LogicManager.java
  src/main/java/seedu/momentum/logic/commands/StartCommand.java
  src/main/java/seedu/momentum/logic/commands/StopCommand.java
  src/main/java/seedu/momentum/model/Model.java
  src/main/java/seedu/momentum/model/ModelManager.java
  src/main/java/seedu/momentum/ui/MainWindow.java
  src/main/java/seedu/momentum/ui/TimerCard.java
  src/main/java/seedu/momentum/ui/TimerListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TimerCard.fxml
  src/main/resources/view/TimerListPanel.fxml
  src/test/java/seedu/momentum/logic/commands/AddCommandTest.java
  src/test/java/seedu/momentum/logic/commands/StartCommandTest.java
  src/test/java/seedu/momentum/logic/commands/StopCommandTest.java
Labels: priority.Medium, type.Task

#78 Add check that deadline has to be after or on created date
  docs/UserGuide.md
  src/main/java/seedu/momentum/commons/core/Date.java
  src/main/java/seedu/momentum/logic/commands/Command.java
  src/main/java/seedu/momentum/logic/commands/EditCommand.java
  src/main/java/seedu/momentum/logic/parser/AddCommandParser.java
  src/main/java/seedu/momentum/logic/parser/EditCommandParser.java
  src/main/java/seedu/momentum/logic/parser/ParserUtil.java
  src/main/java/seedu/momentum/model/project/Deadline.java
  src/main/java/seedu/momentum/model/util/SampleDataUtil.java
  src/main/java/seedu/momentum/storage/JsonAdaptedDeadline.java
  src/main/java/seedu/momentum/storage/JsonAdaptedProject.java
  src/test/data/JsonSerializableProjectBookTest/duplicateProjectProjectBook.json
  src/test/data/JsonSerializableProjectBookTest/typicalProjectsProjectBook.json
  src/test/java/seedu/momentum/logic/commands/CommandTestUtil.java
  src/test/java/seedu/momentum/logic/commands/EditCommandTest.java
  src/test/java/seedu/momentum/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/momentum/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/momentum/logic/parser/ParserUtilTest.java
  src/test/java/seedu/momentum/model/project/DeadlineTest.java
  src/test/java/seedu/momentum/model/project/ProjectTest.java
  src/test/java/seedu/momentum/model/project/UniqueProjectListTest.java
  src/test/java/seedu/momentum/model/project/comparators/CreatedDateCompareTest.java
  src/test/java/seedu/momentum/model/project/comparators/DeadlineCompareTest.java
  src/test/java/seedu/momentum/storage/JsonAdaptedDeadlineTest.java
  src/test/java/seedu/momentum/testutil/EditProjectDescriptorBuilder.java
  src/test/java/seedu/momentum/testutil/ProjectBuilder.java
  src/test/java/seedu/momentum/testutil/TypicalProjects.java
  src/test/java/seedu/momentum/testutil/TypicalProjectsOrders.java
Labels: doc.DevGuide, doc.UserGuide, priority.Medium, type.Enhancement

#79 Update Documentation for Statistics and Timers
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StatsSequenceDiagram.puml
  docs/diagrams/StopTImerSequenceDiagram.puml
  docs/diagrams/TimerDurationClassDiagram.puml
  docs/diagrams/detailed_style.puml
  docs/images/LogicClassDiagram.png
  docs/images/StatsSequenceDiagram.png
  docs/images/StopTImerSequenceDiagram.png
  docs/images/TimerDurationClassDiagram.png
  src/main/java/seedu/momentum/model/timer/Timer.java
Labels: doc.DevGuide, doc.UserGuide, priority.Medium, type.Task

#80 Fix component resizing bug
  src/main/java/seedu/momentum/ui/ProjectCard.java
  src/main/java/seedu/momentum/ui/ProjectListPanel.java
  src/main/java/seedu/momentum/ui/StatCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/Momentum.css
  src/main/resources/view/ProjectListCard.fxml
  src/main/resources/view/ProjectListPanel.fxml
  src/main/resources/view/StatCard.fxml
  src/main/resources/view/TagsDisplay.fxml
  src/main/resources/view/TimerCard.fxml
Labels: severity.Low, type.Bug

#81 Fix tags not updating
  src/main/java/seedu/momentum/ui/MainWindow.java
  src/main/java/seedu/momentum/ui/TagsDisplay.java
Labels: severity.Medium, type.Bug

#84 Enable assertions
  build.gradle
Labels: priority.High, type.Task

#88 Add done command
  src/main/java/seedu/momentum/logic/commands/AddCommand.java
  src/main/java/seedu/momentum/logic/commands/EditCommand.java
  src/main/java/seedu/momentum/logic/commands/FindCommand.java
  src/main/java/seedu/momentum/logic/commands/SortCommand.java
  src/main/java/seedu/momentum/logic/parser/AddCommandParser.java
  src/main/java/seedu/momentum/logic/parser/CliSyntax.java
  src/main/java/seedu/momentum/logic/parser/EditCommandParser.java
  src/main/java/seedu/momentum/logic/parser/FindCommandParser.java
  src/main/java/seedu/momentum/logic/parser/SortCommandParser.java
  src/main/java/seedu/momentum/model/Model.java
  src/main/java/seedu/momentum/model/ModelManager.java
  src/main/java/seedu/momentum/model/ProjectBook.java
  src/main/java/seedu/momentum/model/project/CompletionStatus.java
  src/main/java/seedu/momentum/model/project/Project.java
  src/main/java/seedu/momentum/model/project/Task.java
  src/main/java/seedu/momentum/model/project/TrackedItem.java
  src/main/java/seedu/momentum/model/project/UniqueTrackedItemList.java
  src/main/java/seedu/momentum/model/project/comparators/CompletionStatusCompare.java
  src/main/java/seedu/momentum/model/project/predicates/CompletionStatusPredicate.java
  src/main/java/seedu/momentum/model/util/SampleDataUtil.java
  src/main/java/seedu/momentum/storage/JsonAdaptedProject.java
  src/main/java/seedu/momentum/storage/JsonAdaptedTask.java
  src/main/java/seedu/momentum/ui/TrackedItemCard.java
  src/main/resources/view/Momentum.css
  src/main/resources/view/TrackedItemListCard.fxml
  src/test/data/JsonSerializableProjectBookTest/duplicateProjectProjectBook.json
  src/test/data/JsonSerializableProjectBookTest/typicalProjectsProjectBook.json
  src/test/java/seedu/momentum/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/momentum/logic/commands/AddCommandTest.java
  src/test/java/seedu/momentum/logic/commands/CommandTestUtil.java
  src/test/java/seedu/momentum/logic/commands/EditCommandTest.java
  src/test/java/seedu/momentum/logic/commands/EditTrackedItemDescriptorTest.java
  src/test/java/seedu/momentum/logic/commands/FindCommandTest.java
  src/test/java/seedu/momentum/logic/commands/SortCommandTest.java
  src/test/java/seedu/momentum/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/momentum/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/momentum/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/momentum/logic/parser/ProjectBookParserTest.java
  src/test/java/seedu/momentum/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/momentum/model/ProjectBookTest.java
  src/test/java/seedu/momentum/model/project/CompletionStatusTest.java
  src/test/java/seedu/momentum/model/project/ProjectTest.java
  src/test/java/seedu/momentum/model/project/UniqueTrackedItemListTest.java
  src/test/java/seedu/momentum/model/project/predicates/CompletionStatusPredicateTest.java
  src/test/java/seedu/momentum/model/project/predicates/DescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/momentum/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/momentum/testutil/EditTrackedItemDescriptorBuilder.java
  src/test/java/seedu/momentum/testutil/ProjectBuilder.java
  src/test/java/seedu/momentum/testutil/ProjectUtil.java
  src/test/java/seedu/momentum/testutil/SortCommandUtil.java
  src/test/java/seedu/momentum/testutil/TypicalProjects.java
Labels: doc.DevGuide, doc.UserGuide, priority.Medium, type.Epic

#92 Fix project equals method
  src/main/java/seedu/momentum/logic/commands/AddCommand.java
  src/main/java/seedu/momentum/model/project/Project.java
Labels: priority.High, type.Bug

#95 Update showing and hiding of reminder
  src/main/java/seedu/momentum/logic/commands/EditCommand.java
  src/main/java/seedu/momentum/logic/commands/ShowComponentCommand.java
  src/main/java/seedu/momentum/logic/parser/ParserUtil.java
  src/main/java/seedu/momentum/model/project/TrackedItem.java
  src/main/java/seedu/momentum/model/reminder/Reminder.java
  src/main/java/seedu/momentum/model/util/SampleDataUtil.java
  src/main/java/seedu/momentum/storage/JsonToModel.java
  src/main/java/seedu/momentum/ui/MainWindow.java
  src/test/java/seedu/momentum/logic/commands/CommandTestUtil.java
  src/test/java/seedu/momentum/logic/commands/EditTrackedItemDescriptorTest.java
  src/test/java/seedu/momentum/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/momentum/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/momentum/logic/parser/ParserUtilTest.java
  src/test/java/seedu/momentum/model/ProjectBookTest.java
  src/test/java/seedu/momentum/model/reminder/ReminderTest.java
  src/test/java/seedu/momentum/testutil/EditTrackedItemDescriptorBuilder.java
  src/test/java/seedu/momentum/testutil/ProjectBuilder.java
  src/test/java/seedu/momentum/testutil/TypicalProjects.java
Labels: priority.Medium, severity.Medium, type.Bug

#99 Fix bug for reminder scheduling for tasks
  src/main/java/seedu/momentum/logic/commands/AddCommand.java
  src/main/java/seedu/momentum/logic/commands/DeleteCommand.java
  src/main/java/seedu/momentum/logic/commands/EditCommand.java
  src/main/java/seedu/momentum/logic/commands/StartCommand.java
  src/main/java/seedu/momentum/logic/commands/StopCommand.java
  src/main/java/seedu/momentum/model/Model.java
  src/main/java/seedu/momentum/model/ModelManager.java
  src/test/java/seedu/momentum/logic/commands/AddCommandTest.java
Labels: priority.High, severity.High, type.Bug

#97 Bug Fix
  src/main/java/seedu/momentum/storage/JsonAdaptedTask.java
Labels: severity.High, type.Bug

#109 Fix bug related to show r/
  src/main/java/seedu/momentum/logic/commands/ShowComponentCommand.java
  src/test/java/seedu/momentum/logic/commands/ShowComponentCommandTest.java
Labels: priority.High, severity.High, type.Bug

#117 Add Undo/redo feature
  src/main/java/seedu/momentum/logic/commands/AddCommand.java
  src/main/java/seedu/momentum/logic/commands/ClearCommand.java
  src/main/java/seedu/momentum/logic/commands/DeleteCommand.java
  src/main/java/seedu/momentum/logic/commands/EditCommand.java
  src/main/java/seedu/momentum/logic/commands/FindCommand.java
  src/main/java/seedu/momentum/logic/commands/HomeCommand.java
  src/main/java/seedu/momentum/logic/commands/ListCommand.java
  src/main/java/seedu/momentum/logic/commands/ProjectViewCommand.java
  src/main/java/seedu/momentum/logic/commands/RedoCommand.java
  src/main/java/seedu/momentum/logic/commands/ShowComponentCommand.java
  src/main/java/seedu/momentum/logic/commands/SortCommand.java
  src/main/java/seedu/momentum/logic/commands/StartCommand.java
  src/main/java/seedu/momentum/logic/commands/StopCommand.java
  src/main/java/seedu/momentum/logic/commands/UndoCommand.java
  src/main/java/seedu/momentum/logic/parser/ProjectBookParser.java
  src/main/java/seedu/momentum/model/Model.java
  src/main/java/seedu/momentum/model/ModelManager.java
  src/main/java/seedu/momentum/model/ProjectBook.java
  src/main/java/seedu/momentum/model/ProjectBookWithUi.java
  src/main/java/seedu/momentum/model/VersionedProjectBook.java
  src/main/java/seedu/momentum/model/project/Project.java
  src/main/java/seedu/momentum/model/project/UniqueTrackedItemList.java
  src/main/java/seedu/momentum/model/reminder/ReminderManager.java
  src/test/java/seedu/momentum/logic/LogicManagerTest.java
  src/test/java/seedu/momentum/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/momentum/logic/commands/AddCommandTest.java
  src/test/java/seedu/momentum/logic/commands/ClearCommandTest.java
  src/test/java/seedu/momentum/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/momentum/logic/commands/EditCommandTest.java
  src/test/java/seedu/momentum/logic/commands/FindCommandTest.java
  src/test/java/seedu/momentum/logic/commands/ListCommandTest.java
  src/test/java/seedu/momentum/logic/commands/SortCommandTest.java
  src/test/java/seedu/momentum/logic/commands/StartCommandTest.java
  src/test/java/seedu/momentum/logic/commands/StopCommandTest.java
  src/test/java/seedu/momentum/model/reminder/ReminderManagerTest.java
Labels: priority.Medium, type.Story, type.Task

#114 Update MainWindow.java to fix size of reminder panel
  src/main/java/seedu/momentum/ui/MainWindow.java
Labels: priority.High, severity.High, type.Bug

#122 Fix app closing bug
  src/main/java/seedu/momentum/MainApp.java
Labels: priority.High, type.Bug

#125 Fixed UI for Windows
  src/main/java/seedu/momentum/commons/core/Theme.java
  src/main/java/seedu/momentum/ui/TrackedItemCard.java
Labels: priority.High, severity.High, type.Bug

#126 Fix typo in CompletionStatusPredicate
  src/main/java/seedu/momentum/model/project/predicates/CompletionStatusPredicate.java
Labels: priority.Medium, severity.VeryLow, type.Bug

#127 Update dummy data and documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/momentum/model/util/SampleDataUtil.java
  src/main/resources/view/TrackedItemListCard.fxml
Labels: priority.Medium, severity.Medium

#183 Make invalid command turn red
  src/main/resources/view/MomentumDark.css
  src/main/resources/view/MomentumLight.css
Labels: severity.VeryLow, type.Bug
